// Generated by TinyPG v1.3 available at www.codeproject.com

using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Xml.Serialization;

namespace Mizu2.Parser
{
    #region Scanner

    public partial class Scanner
    {
        public string Input;
        public int StartPos = 0;
        public int EndPos = 0;
        public int CurrentLine;
        public int CurrentColumn;
        public int CurrentPosition;
        public List<Token> Skipped; // tokens that were skipped
        public Dictionary<TokenType, Regex> Patterns;

        private Token LookAheadToken;
        private List<TokenType> Tokens;
        private List<TokenType> SkipList; // tokens to be skipped

        public Scanner()
        {
            Regex regex;
            Patterns = new Dictionary<TokenType, Regex>();
            Tokens = new List<TokenType>();
            LookAheadToken = null;
            Skipped = new List<Token>();

            SkipList = new List<TokenType>();

            regex = new Regex(@"\<", RegexOptions.Compiled);
            Patterns.Add(TokenType.GT, regex);
            Tokens.Add(TokenType.GT);

            regex = new Regex(@"\<\=", RegexOptions.Compiled);
            Patterns.Add(TokenType.GTE, regex);
            Tokens.Add(TokenType.GTE);

            regex = new Regex(@"\=\=", RegexOptions.Compiled);
            Patterns.Add(TokenType.DEQUAL, regex);
            Tokens.Add(TokenType.DEQUAL);

            regex = new Regex(@"\>", RegexOptions.Compiled);
            Patterns.Add(TokenType.LT, regex);
            Tokens.Add(TokenType.LT);

            regex = new Regex(@"\>\=", RegexOptions.Compiled);
            Patterns.Add(TokenType.LTE, regex);
            Tokens.Add(TokenType.LTE);

            regex = new Regex(@"(\!\=|\<\>)", RegexOptions.Compiled);
            Patterns.Add(TokenType.NOTEQUAL, regex);
            Tokens.Add(TokenType.NOTEQUAL);

            regex = new Regex(@"\{", RegexOptions.Compiled);
            Patterns.Add(TokenType.OPENBRCK, regex);
            Tokens.Add(TokenType.OPENBRCK);

            regex = new Regex(@"\}", RegexOptions.Compiled);
            Patterns.Add(TokenType.CLOSEBRCK, regex);
            Tokens.Add(TokenType.CLOSEBRCK);

            regex = new Regex(@"\"".+?\""", RegexOptions.Compiled);
            Patterns.Add(TokenType.STRING, regex);
            Tokens.Add(TokenType.STRING);

            regex = new Regex(@"\,", RegexOptions.Compiled);
            Patterns.Add(TokenType.COMMA, regex);
            Tokens.Add(TokenType.COMMA);

            regex = new Regex(@"(\r\n|\n)", RegexOptions.Compiled);
            Patterns.Add(TokenType.NEWLINE, regex);
            Tokens.Add(TokenType.NEWLINE);

            regex = new Regex(@"\=", RegexOptions.Compiled);
            Patterns.Add(TokenType.EQUAL, regex);
            Tokens.Add(TokenType.EQUAL);

            regex = new Regex(@"\s+", RegexOptions.Compiled);
            Patterns.Add(TokenType.WHITESPACE, regex);
            Tokens.Add(TokenType.WHITESPACE);

            regex = new Regex(@"\[", RegexOptions.Compiled);
            Patterns.Add(TokenType.OPENBR, regex);
            Tokens.Add(TokenType.OPENBR);

            regex = new Regex(@"\]", RegexOptions.Compiled);
            Patterns.Add(TokenType.CLOSEBR, regex);
            Tokens.Add(TokenType.CLOSEBR);

            regex = new Regex(@"\.", RegexOptions.Compiled);
            Patterns.Add(TokenType.PERIOD, regex);
            Tokens.Add(TokenType.PERIOD);

            regex = new Regex(@"\:", RegexOptions.Compiled);
            Patterns.Add(TokenType.COLON, regex);
            Tokens.Add(TokenType.COLON);

            regex = new Regex(@"\+", RegexOptions.Compiled);
            Patterns.Add(TokenType.PLUS, regex);
            Tokens.Add(TokenType.PLUS);

            regex = new Regex(@"\-", RegexOptions.Compiled);
            Patterns.Add(TokenType.MINUS, regex);
            Tokens.Add(TokenType.MINUS);

            regex = new Regex(@"\*", RegexOptions.Compiled);
            Patterns.Add(TokenType.MULTI, regex);
            Tokens.Add(TokenType.MULTI);

            regex = new Regex(@"\/", RegexOptions.Compiled);
            Patterns.Add(TokenType.DIV, regex);
            Tokens.Add(TokenType.DIV);

            regex = new Regex(@"^\s*$", RegexOptions.Compiled);
            Patterns.Add(TokenType.EOF, regex);
            Tokens.Add(TokenType.EOF);

            regex = new Regex(@"\t", RegexOptions.Compiled);
            Patterns.Add(TokenType.TAB, regex);
            Tokens.Add(TokenType.TAB);

            regex = new Regex(@"\s\s\s\s", RegexOptions.Compiled);
            Patterns.Add(TokenType.FOURSPACE, regex);
            Tokens.Add(TokenType.FOURSPACE);

            regex = new Regex(@"(?!(uses|var|if|for))[a-zA-Z][a-zA-Z0-9_]*", RegexOptions.Compiled);
            Patterns.Add(TokenType.IDENTIFIER, regex);
            Tokens.Add(TokenType.IDENTIFIER);

            regex = new Regex(@"(\-)?[0-9]+", RegexOptions.Compiled);
            Patterns.Add(TokenType.NUMBER, regex);
            Tokens.Add(TokenType.NUMBER);

            regex = new Regex(@"(\-)?[0-9]+\.[0-9]+", RegexOptions.Compiled);
            Patterns.Add(TokenType.FLOAT, regex);
            Tokens.Add(TokenType.FLOAT);

            regex = new Regex(@"(?!(\s|\n))[a-zA-Z_]*(\.[a-zA-Z0-9_]*)?", RegexOptions.Compiled);
            Patterns.Add(TokenType.NAMESPACE, regex);
            Tokens.Add(TokenType.NAMESPACE);

            regex = new Regex(@"\b(?!(uses|var|if|for))[a-zA-Z0-9_]*((\.[a-zA-Z0-9_]*)?)*\b", RegexOptions.Compiled);
            Patterns.Add(TokenType.TYPE, regex);
            Tokens.Add(TokenType.TYPE);

            regex = new Regex(@"(null|nil)", RegexOptions.Compiled);
            Patterns.Add(TokenType.NULLKW, regex);
            Tokens.Add(TokenType.NULLKW);

            regex = new Regex(@"class", RegexOptions.Compiled);
            Patterns.Add(TokenType.CLASSKW, regex);
            Tokens.Add(TokenType.CLASSKW);

            regex = new Regex(@"public", RegexOptions.Compiled);
            Patterns.Add(TokenType.PUBLICKW, regex);
            Tokens.Add(TokenType.PUBLICKW);

            regex = new Regex(@"private", RegexOptions.Compiled);
            Patterns.Add(TokenType.PRIVATEKW, regex);
            Tokens.Add(TokenType.PRIVATEKW);

            regex = new Regex(@"(P|p)ublic class", RegexOptions.Compiled);
            Patterns.Add(TokenType.PUBLICCLASSKW, regex);
            Tokens.Add(TokenType.PUBLICCLASSKW);

            regex = new Regex(@"(P|p)rivate class", RegexOptions.Compiled);
            Patterns.Add(TokenType.PRIVATECLASSKW, regex);
            Tokens.Add(TokenType.PRIVATECLASSKW);

            regex = new Regex(@"def", RegexOptions.Compiled);
            Patterns.Add(TokenType.DEFKW, regex);
            Tokens.Add(TokenType.DEFKW);

            regex = new Regex(@"(P|p)ublic def", RegexOptions.Compiled);
            Patterns.Add(TokenType.PUBLICDEFKW, regex);
            Tokens.Add(TokenType.PUBLICDEFKW);

            regex = new Regex(@"(P|p)rivate def", RegexOptions.Compiled);
            Patterns.Add(TokenType.PRIVATEDEFKW, regex);
            Tokens.Add(TokenType.PRIVATEDEFKW);

            regex = new Regex(@"\(", RegexOptions.Compiled);
            Patterns.Add(TokenType.BROPEN, regex);
            Tokens.Add(TokenType.BROPEN);

            regex = new Regex(@"\)", RegexOptions.Compiled);
            Patterns.Add(TokenType.BRCLOSE, regex);
            Tokens.Add(TokenType.BRCLOSE);

            regex = new Regex(@"if", RegexOptions.Compiled);
            Patterns.Add(TokenType.IFKW, regex);
            Tokens.Add(TokenType.IFKW);

            regex = new Regex(@"true", RegexOptions.Compiled);
            Patterns.Add(TokenType.TRUE, regex);
            Tokens.Add(TokenType.TRUE);

            regex = new Regex(@"false", RegexOptions.Compiled);
            Patterns.Add(TokenType.FALSE, regex);
            Tokens.Add(TokenType.FALSE);

            regex = new Regex(@"var", RegexOptions.Compiled);
            Patterns.Add(TokenType.VAR, regex);
            Tokens.Add(TokenType.VAR);

            regex = new Regex(@"new", RegexOptions.Compiled);
            Patterns.Add(TokenType.NEW, regex);
            Tokens.Add(TokenType.NEW);

            regex = new Regex(@"as", RegexOptions.Compiled);
            Patterns.Add(TokenType.AS, regex);
            Tokens.Add(TokenType.AS);

            regex = new Regex(@"else", RegexOptions.Compiled);
            Patterns.Add(TokenType.ELSE, regex);
            Tokens.Add(TokenType.ELSE);

            regex = new Regex(@"for", RegexOptions.Compiled);
            Patterns.Add(TokenType.FOR, regex);
            Tokens.Add(TokenType.FOR);

            regex = new Regex(@"in", RegexOptions.Compiled);
            Patterns.Add(TokenType.IN, regex);
            Tokens.Add(TokenType.IN);

            regex = new Regex(@"uses", RegexOptions.Compiled);
            Patterns.Add(TokenType.USES, regex);
            Tokens.Add(TokenType.USES);


        }

        public void Init(string input)
        {
            this.Input = input;
            StartPos = 0;
            EndPos = 0;
            CurrentLine = 0;
            CurrentColumn = 0;
            CurrentPosition = 0;
            LookAheadToken = null;
        }

        public Token GetToken(TokenType type)
        {
            Token t = new Token(this.StartPos, this.EndPos);
            t.Type = type;
            return t;
        }

         /// <summary>
        /// executes a lookahead of the next token
        /// and will advance the scan on the input string
        /// </summary>
        /// <returns></returns>
        public Token Scan(params TokenType[] expectedtokens)
        {
            Token tok = LookAhead(expectedtokens); // temporarely retrieve the lookahead
            LookAheadToken = null; // reset lookahead token, so scanning will continue
            StartPos = tok.EndPos;
            EndPos = tok.EndPos; // set the tokenizer to the new scan position
            return tok;
        }

        /// <summary>
        /// returns token with longest best match
        /// </summary>
        /// <returns></returns>
        public Token LookAhead(params TokenType[] expectedtokens)
        {
            int i;
            int startpos = StartPos;
            Token tok = null;
            List<TokenType> scantokens;


            // this prevents double scanning and matching
            // increased performance
            if (LookAheadToken != null 
                && LookAheadToken.Type != TokenType._UNDETERMINED_ 
                && LookAheadToken.Type != TokenType._NONE_) return LookAheadToken;

            // if no scantokens specified, then scan for all of them (= backward compatible)
            if (expectedtokens.Length == 0)
                scantokens = Tokens;
            else
            {
                scantokens = new List<TokenType>(expectedtokens);
                scantokens.AddRange(SkipList);
            }

            do
            {

                int len = -1;
                TokenType index = (TokenType)int.MaxValue;
                string input = Input.Substring(startpos);

                tok = new Token(startpos, EndPos);

                for (i = 0; i < scantokens.Count; i++)
                {
                    Regex r = Patterns[scantokens[i]];
                    Match m = r.Match(input);
                    if (m.Success && m.Index == 0 && ((m.Length > len) || (scantokens[i] < index && m.Length == len )))
                    {
                        len = m.Length;
                        index = scantokens[i];  
                    }
                }

                if (index >= 0 && len >= 0)
                {
                    tok.EndPos = startpos + len;
                    tok.Text = Input.Substring(tok.StartPos, len);
                    tok.Type = index;
                }
                else if (tok.StartPos < tok.EndPos - 1)
                {
                    tok.Text = Input.Substring(tok.StartPos, 1);
                }

                if (SkipList.Contains(tok.Type))
                {
                    startpos = tok.EndPos;
                    Skipped.Add(tok);
                }
                else
                {
                    // only assign to non-skipped tokens
                    tok.Skipped = Skipped; // assign prior skips to this token
                    Skipped = new List<Token>(); //reset skips
                }
            }
            while (SkipList.Contains(tok.Type));

            LookAheadToken = tok;
            return tok;
        }
    }

    #endregion

    #region Token

    public enum TokenType
    {

            //Non terminal tokens:
            _NONE_  = 0,
            _UNDETERMINED_= 1,

            //Non terminal tokens:
            Start   = 2,
            Boolean = 3,
            Assignment= 4,
            VariableAssignment= 5,
            VariableExpr= 6,
            Statement= 7,
            Type    = 8,
            IfStatement= 9,
            IfStmtIFBody= 10,
            IfStmtELSEBody= 11,
            Operator= 12,
            Indention= 13,
            FuncCall= 14,
            MathExpr= 15,
            ForStatement= 16,
            ForEachStmt= 17,
            ForIterStmt= 18,
            ForStmtBODY= 19,
            UsesStatement= 20,

            //Terminal tokens:
            GT      = 21,
            GTE     = 22,
            DEQUAL  = 23,
            LT      = 24,
            LTE     = 25,
            NOTEQUAL= 26,
            OPENBRCK= 27,
            CLOSEBRCK= 28,
            STRING  = 29,
            COMMA   = 30,
            NEWLINE = 31,
            EQUAL   = 32,
            WHITESPACE= 33,
            OPENBR  = 34,
            CLOSEBR = 35,
            PERIOD  = 36,
            COLON   = 37,
            PLUS    = 38,
            MINUS   = 39,
            MULTI   = 40,
            DIV     = 41,
            EOF     = 42,
            TAB     = 43,
            FOURSPACE= 44,
            IDENTIFIER= 45,
            NUMBER  = 46,
            FLOAT   = 47,
            NAMESPACE= 48,
            TYPE    = 49,
            NULLKW  = 50,
            CLASSKW = 51,
            PUBLICKW= 52,
            PRIVATEKW= 53,
            PUBLICCLASSKW= 54,
            PRIVATECLASSKW= 55,
            DEFKW   = 56,
            PUBLICDEFKW= 57,
            PRIVATEDEFKW= 58,
            BROPEN  = 59,
            BRCLOSE = 60,
            IFKW    = 61,
            TRUE    = 62,
            FALSE   = 63,
            VAR     = 64,
            NEW     = 65,
            AS      = 66,
            ELSE    = 67,
            FOR     = 68,
            IN      = 69,
            USES    = 70
    }

    public class Token
    {
        private int startpos;
        private int endpos;
        private string text;
        private object value;

        // contains all prior skipped symbols
        private List<Token> skipped;

        public int StartPos { 
            get { return startpos;} 
            set { startpos = value; }
        }

        public int Length { 
            get { return endpos - startpos;} 
        }

        public int EndPos { 
            get { return endpos;} 
            set { endpos = value; }
        }

        public string Text { 
            get { return text;} 
            set { text = value; }
        }

        public List<Token> Skipped { 
            get { return skipped;} 
            set { skipped = value; }
        }
        public object Value { 
            get { return value;} 
            set { this.value = value; }
        }

        [XmlAttribute]
        public TokenType Type;

        public Token()
            : this(0, 0)
        {
        }

        public Token(int start, int end)
        {
            Type = TokenType._UNDETERMINED_;
            startpos = start;
            endpos = end;
            Text = ""; // must initialize with empty string, may cause null reference exceptions otherwise
            Value = null;
        }

        public void UpdateRange(Token token)
        {
            if (token.StartPos < startpos) startpos = token.StartPos;
            if (token.EndPos > endpos) endpos = token.EndPos;
        }

        public override string ToString()
        {
            if (Text != null)
                return Type.ToString() + " '" + Text + "'";
            else
                return Type.ToString();
        }
    }

    #endregion
}
